[platformio]
src_dir = main
default_envs = esp32-s3-devkitc-1

[env:esp32-s3-devkitc-1]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.312-1/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
build_src_filter = +<controller.cpp> +<main.cpp> +<display.cpp> +<mic.cpp> +<haptics.cpp>
build_flags = -DARDUINO_USB_CDC_ON_BOOT=0
lib_deps =
    adafruit/Adafruit SSD1351 library@1.3.3
    adafruit/Adafruit GFX Library@1.12.6
    adafruit/Adafruit DRV2605 Library@1.2.4
    adafruit/Adafruit BusIO@1.17.4
